### ISSUE TITLE
Several error

### ISSUE THREAD

**Issue by Lee-JaeWon** [Florian-Barthel/gaussian_viewer#1]
Thank you for your work.

To test your good work, I tried to follow the instructions given in the README.md.

I have two problems

In environment.yml, it seems to be `gaussian-splatting/submodules/diff-gaussian-rasterization-custom` and not `gaussian-splatting/submodules/diff-gaussian-rasterization`.

I git cloned it with --recursive but just `diff-gaussian-rasterization` is empty.

The second issue is that in `./widgets/video_widge.py`, the `from scene.cameras import CustomCam` is not working.
It looks like vanila gs is not importing well.

What should I do?

I'd like to contribute to your work after I've tested it enough.

And FYI, it doesn't seem to work on CUDA 11.7 or lower.

Thank you.

**Comment by Florian-Barthel** [comment]
Hey, thanks for participating! 

I have updated the submodules so that they are no longer hardcoded but instead linked to the respective repository. I hope this resolves the first issue. You might have to clone the repository again, to make it work.

The second issue can hopefully be resolved by adding the "gaussian-splatting" folder to the python path. I have added the line ` sys.path.append("./gaussian-splatting")` to main.py. Let me know if this works.

Do you have an idea, why CUDA 11.7 is not working properly?

**Comment by Lee-JaeWon** [comment]
Thank you for your quick response.

I cloned it again and the UI is working.

However, I'm facing a new problem

I set the training result of vanilla gaussian splatting to the path --data_path.

I think I missed something in this, could you please tell me?

The error is as below.

```
~/workspace/src# python main.py --data_path="/root/workspace/src/output/8467a616-9/"

Traceback (most recent call last):
  File "/root/workspace/src/viz/renderer.py", line 47, in render
    self._render_impl(res, **args)
  File "/root/workspace/src/viz/renderer.py", line 102, in _render_impl
    self.gaussian_model.load_ply(ply_file_path)
  File "/root/workspace/src/./gaussian-splatting/scene/gaussian_model.py", line 258, in load_ply
    opacities = np.asarray(plydata.elements[0]["opacity"])[..., np.newaxis]
  File "/opt/conda/envs/gs-view/lib/python3.10/site-packages/plyfile.py", line 715, in __getitem__
    return self.data[key]
  File "/opt/conda/envs/gs-view/lib/python3.10/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name opacity

```

**Comment by Lee-JaeWon** [comment]
Never mind the last issue. The path was invalid.

When I set the path correctly, I see an array for _xyz or _opacity. But all I see is a black window.

![Screenshot from 2024-03-05 20-27-21](https://github.com/Florian-Barthel/gaussian_viewer/assets/72693388/359a67ce-bd21-4ac8-bc1d-080c669360fa)

**Comment by Lee-JaeWon** [comment]
The renderer seems to be working fine.

However, the Gaussians that I have are relative to a different coordinate system and have large values, which I think is why they don't show up.

**Comment by Florian-Barthel** [comment]
Okay, thats good news that the renderer is working properly. With the mouse wheel, you can zoom out further that with the UI. Maybe, that helps rendering very large scenes. I will look into building a feature that autodetects the center of the scene and also adjusts the zoom to the size of the scene

**Comment by Florian-Barthel** [comment]
I have just pushed a new feature that autodetects the center of the scene and adjusts the radius. The new buttons can be found in the camera widget. I hope this helps to properly render the scene.
It uses the mean xyz as center and stddev of xyz as radius

If there are no more questions, I will close this issue
