### ISSUE TITLE
some discuss

### ISSUE THREAD

**Issue by Bin-ze** [Florian-Barthel/gaussian_viewer#11]
Thank you very much for your work!
I hope to try to implement some customized functions with the simplest implementation:
1. I hope to render several scenes at the same time
2. Each sub-scene can be selected at the same time
3. Each sub-scene can be rotated, scaled, translated, etc.
4. The edited scene can be exported

In fact, I have implemented a large part of the content, but due to the limitations of the tool, the functions are all implemented manually by myself, which may make the editing function not easy to use. Do you have any suggestions?

**Comment by Florian-Barthel** [comment]
Hi,
its nice to hear that you are motivated to add some functionality to the viewer! I also wanted to implement a feature that allows viewing different scenes at the same time. My idea was to create some kind of split screen view that helps to compare the same scene from different trainings.

For your usecase, to rotate and edit each scene separately, it might make sense to create a wrapper class that holds the whole viewer and all its parameters. Then it might be easier to duplicate the functionality multiple times. In this case you could dynamically add further independent viewer instances.

I will create a branch for this idea. You can create a Pull Request for that branch with your current changes if you want to collaborate.

**Comment by Florian-Barthel** [comment]
Hi,

I have just pushed a new version that allows viewing multiple scenes side by side. Its not nearly in the state, which you described, where each scene can be edited independently. However, it might be a good starting point for future work.

**Comment by Bin-ze** [comment]
Hi, thank you very much for your work, it is very useful. 

On the other hand, [supersplat](https://playcanvas.com/supersplat/editor) already supports all the functions I mentioned, maybe you can refer to its implementation.
