### ISSUE TITLE
some more bug

### ISSUE THREAD

**Issue by oUp2Uo** [Florian-Barthel/gaussian_viewer#3]
And I found some more bug.
When try to record video more than one time,
and just change some camera parameter like fov / radius / height (not sure which on is actually effect),
sometimes y axis could be inverted.

Also the video render result is a bit weird.
Does `Size` in `Camera` have effect on the video render result?
And what does this `Size` mean?
I have tried to enlarge this parameter, and OOM immediately.

Btw, if there could have a preview function in `video` part, for example, click once to generate one sample image,
I think it will be easier to confirm if the parameter is set well.

And if there could have rotating speed and x/y resolution setting paramter,
the `video` part will be better.

**Comment by Florian-Barthel** [comment]
Yes, currently the Video tab is a little bit missleading, as it using a camera that completely unrelated to the parameters of the camera tab. I will think of a way to clarify this.

I could not reproduce the error, where the y axis is inverted, but I will look into this.

Setting x and y individually is a good idea. Thanks for the recommendation!

**Comment by oUp2Uo** [comment]
> it using a camera that completely unrelated to the parameters of the camera tab. I will think of a way to clarify this.

Yes, I have noticed that after some test.
The camera parameter changed in `Camera` tag is also needed in `Video`, I think.
(Which means `Video` just setting the camera look-at point to (0, height, 0) and rotating around horizontally at distance Radius by speed xxx.
Of course, if the look-at point xyz could all be set manually, rotating vector(direction)/speed could be set manually would be cool.)

**Comment by Florian-Barthel** [comment]
Hi,
i have fixed the FOV value for the video generation. I somehow mixed up degrees and radians. 

Nevertheless, the camera from the video tab and the camera from the camera tab are still different. I will look into this soon, in order to make it more intuitive.
