### ISSUE TITLE
interactive viewer

### ISSUE THREAD

**Issue by ZhenWusi** [Florian-Barthel/gaussian_viewer#4]
How can I use my .ply files to interactive viewer?

**Comment by Florian-Barthel** [comment]
Hi,

you can launch the main.py file like this:

**Comment by Florian-Barthel** [comment]
Hi,
you can launch the main.py file like this:

`python main.py --data_path="path/to/directory/with/gaussian/objects"`

The viewer then searches for .ply files in all subdirectories of the data_path you select. Just press browse in the viewer and select the ply file you want to inspect
