### ISSUE TITLE
how can I fix GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'

### ISSUE THREAD

**Issue by ZhenWusi** [Florian-Barthel/gaussian_viewer#5]
When I run python main.py --data_path="path/to/directory/with/gaussian/objects happen that
<img width="766" alt="屏幕截图 2024-03-09 151913" src="https://github.com/Florian-Barthel/gaussian_viewer/assets/105499590/a8d9b7ac-30c5-4266-8a46-caba108b160c">

**Comment by Florian-Barthel** [comment]
Hi,
it looks like the display env variable is not set properly. Try running this line before launching main.py:

`export DISPLAY=:0.0`

(from https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean)

**Comment by ZhenWusi** [comment]
thanks! I fix it.
