### ISSUE TITLE
 how to use the video component? 

### ISSUE THREAD

**Issue by ZhenWusi** [Florian-Barthel/gaussian_viewer#6]
Can you explain the parameters in the video component, for example, I want to get a video of the ship dataset circling the ship, but the ship can't be displayed in a positive way

**Comment by ZhenWusi** [comment]
![Uploading 屏幕截图 2024-03-15 180526.png…]()

**Comment by ZhenWusi** [comment]
Thank you very much, you understood what I meant. Now I want to use my own point cloud file to generate a video of a circle around the object, can you help me make the video smooth [https://drive.google.com/file/d/1gzF7yfngRgMR9nue4LMlpaYPuS1mmmQT/view?usp=sharing er?]

**Comment by ZhenWusi** [comment]
Thank you very much, you understood what I meant. Now I want to use my own point cloud file to generate a video of a circle around the object, can you help me make the video smooth [](https://drive.google.com/file/d/1gzF7yfngRgMR9nue4LMlpaYPuS1mmmQT/view?usp=sharing)

**Comment by ZhenWusi** [comment]
Thank you very much, you understood what I meant. Now I want to use my own point cloud file to generate a video of a circle around the object, can you help me make the video smooth https://drive.google.com/file/d/1gzF7yfngRgMR9nue4LMlpaYPuS1mmmQT/view?usp=sharing er?[https://drive.google.com/file/d/1gzF7yfngRgMR9nue4LMlpaYPuS1mmmQT/view?usp=sharing er?](url)

**Comment by Florian-Barthel** [comment]
Does this look right?

https://github.com/Florian-Barthel/gaussian_viewer/assets/38436810/cde33b76-9281-4b00-ba72-077d57be91d8
